name: build

on:
    push:
        tags:
            - "v*"
        branches:
            - "main"
        paths:
            - ".github/workflows/build.yml"
            - "3rdparty/**"
            - "cmake/**"
            - "include/**"
            - "source/**"
            - "CMakeLists.txt"
            - "tools/pip_pack/**"

    pull_request:
        branches:
            - "**"
        paths:
            - ".github/workflows/build.yml"
            - "3rdparty/**"
            - "cmake/**"
            - "include/**"
            - "source/**"
            - "CMakeLists.txt"
            - "tools/pip_pack/**"

    workflow_dispatch:
        inputs:
            build-config:
                required: true
                default: "RelWithDebInfo"
                type: choice
                options:
                    - Debug
                    - RelWithDebInfo
                    - Release
            with-dbg-controller:
                required: false
                default: false
                type: boolean
                description: "Build with debug controller (MaaDbgControlUnit.dll)"

    repository_dispatch:
        types: [MaaUtilsUpdated]

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.head.repo.full_name || github.repository }}-${{ github.head_ref || github.ref_name }}${{ github.ref == 'refs/heads/main' && format('-{0}', github.sha) || '' }}
    cancel-in-progress: true

jobs:
    meta:
        uses: ./.github/workflows/meta.yml
        with:
            build-config: ${{ inputs.build-config || 'RelWithDebInfo' }}


    windows:
        needs: meta
        runs-on: windows-latest
        strategy:
            matrix:
                arch: [x86_64]
            fail-fast: false

        steps:
            - name: Windows runner hack
              shell: cmd
              run: |
                  dir d:\a
                  cd ..
                  mkdir C:\MaaFramework
                  rmdir MaaFramework
                  mklink /j MaaFramework C:\MaaFramework
                  dism /Online /Disable-Feature /FeatureName:Windows-Defender /Remove /NoRestart /Quiet
                  cd .

            - name: Windows runner hack (2)
              uses: al-cheb/configure-pagefile-action@v1.4
              with:
                  minimum-size: 16GB
                  maximum-size: 16GB
                  disk-root: "D:"

            - uses: actions/checkout@v4
              with:
                  submodules: true

            - name: Update MaaUtils
              if: github.event_name == 'repository_dispatch' && github.event.action == 'MaaUtilsUpdated'
              run: |
                  git submodule update --remote source/MaaUtils

            - name: Setup Windows 10 SDK
              uses: GuillaumeFalourd/setup-windows10-sdk-action@v2.2
              with:
                  sdk-version: 26100

            - name: Cache MaaDeps
              id: cache-maadeps
              uses: actions/cache@v4
              with:
                  path: |
                      ./source/MaaUtils/MaaDeps
                  key: maadeps-${{ runner.os }}-${{ matrix.arch }}-${{ hashFiles('./tools/maadeps-download.py') }}

            - name: Bootstrap MaaDeps
              if: steps.cache-maadeps.outputs.cache-hit != 'true'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  python3 tools/maadeps-download.py ${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}-windows

            - uses: pnpm/action-setup@v4
              with:
                  version: latest

            - name: Use Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20

            - name: Prepare node_modules
              run: |
                  cd source/binding/NodeJS
                  pnpm i
                  cd -

            - name: Build MAA
              run: |
                  cmake --preset "${{ matrix.arch == 'x86_64' && 'MSVC 2022' || 'MSVC 2022 ARM' }}" -DCMAKE_SYSTEM_VERSION="10.0.26100.0" -DMAADEPS_TRIPLET="maa-${{ matrix.arch == 'x86_64' && 'x64' || 'arm64' }}-windows" -DMAA_HASH_VERSION='${{ needs.meta.outputs.tag }}' -DWITH_NODEJS_BINDING=ON -DWITH_QUICKJS_BINDING=ON -DWITH_DBG_CONTROLLER=${{ github.event_name == 'workflow_dispatch' && inputs.with-dbg-controller == true && 'ON' || 'OFF' }}

                  cmake --build build --preset "${{ matrix.arch == 'x86_64' && 'MSVC 2022' || 'MSVC 2022 ARM' }} - ${{ needs.meta.outputs.build-config }}" -j 16

            - name: Install
              shell: bash
              run: |
                  cmake --install build --prefix install --config ${{ needs.meta.outputs.build-config }}
                  rm -rf install/bin/msvc-debug

                  cp -r docs install
                  cp README*.md install

                  cp -r sample install

                  cp -r LICENSE.md install

            - name: Download Plugin
              uses: robinraju/release-downloader@v1
              with:
                  repository: MaaXYZ/MaaPluginDemo
                  tag: ${{ needs.meta.outputs.latest-plugin }}
                  fileName: "*win-${{ matrix.arch }}*"
                  out-file-path: "build/download_plugins"
                  extract: true
                  token: ${{ secrets.GITHUB_TOKEN }}

            - name: Install Plugin
              shell: bash
              run: |
                  cp -r build/download_plugins/bin install/bin/plugins

            - uses: actions/upload-artifact@v4
              if: always()
              with:
                  name: MAA-win-${{ matrix.arch }}
                  path: "install"


